# Generated by Django 2.2.7 on 2019-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_test_sphere_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.IntegerField(default=1, max_length=5, verbose_name='Кількість спроб'),
        ),
    ]
