# Generated by Django 2.2.7 on 2019-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_test_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sphere_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ID завдання в sphere engine'),
        ),
    ]
