# Generated by Django 2.2.7 on 2019-12-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191211_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.AlterField(
            model_name='test',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Кількість спроб'),
        ),
        migrations.CreateModel(
            name='Test_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(default='Тестове завдання', max_length=100, verbose_name='Назва роботи')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Test_case'),
            preserve_default=False,
        ),
    ]
