# Generated by Django 2.2.7 on 2019-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20191211_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_case',
            name='case_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва роботи'),
        ),
    ]
