# Generated by Django 2.2.7 on 2019-12-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_delete_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Одиночне завдання', 'verbose_name_plural': 'Одиночні завдання'},
        ),
        migrations.AlterModelOptions(
            name='test_case',
            options={'verbose_name': 'Тестове завдання', 'verbose_name_plural': 'Тестові завдання'},
        ),
        migrations.AddField(
            model_name='test_case',
            name='case_duration',
            field=models.IntegerField(default=600),
        ),
    ]
