# Generated by Django 2.2.7 on 2019-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20191211_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_case',
            name='case_duration',
            field=models.IntegerField(default=10),
        ),
    ]
